
DROP TABLE AIRPORT;
DROP TABLE ROUTE;
DROP TABLE AIRCRAFT;
DROP TABLE SCHEDULE;
DROP TABLE TRAVELAGENT;
DROP TABLE CUSTOMER;
DROP TABLE SERVICEITEM;
DROP TABLE FLIGHT;
DROP TABLE FLIGHTSERVICE;
DROP TABLE STAFF;
DROP TABLE BOOKING;
DROP TABLE MESSAGE;
DROP  TABLE SEAT;