SET ECHO ON
SET FEEDBACK ON

CREATE TABLE AIRPORT(
	id		NUMBER(4)	NOT NULL,
	name 		VARCHAR(50)	NOT NULL,
	city		VARCHAR(50)	NOT NULL,
	country		VARCHAR(50)	NOT NULL,
	iata		VARCHAR(3)	NOT NULL,
	latitude	DECIMAL(10,6)	NOT NULL,
	longitude	DECIMAL(10,6)	NOT NULL,
	altitude	NUMBER(5)	NOT NULL,
	timezone	NUMBER(2)	NOT NULL,
	DST		CHAR(1)		NOT NULL,
	tz		VARCHAR(50)	NOT NULL,
	CONSTRAINT AIRPORT_pkey PRIMARY KEY (id),
	CONSTRAINT airport_iata UNIQUE (iata),
	CONSTRAINT alt_check CHECK (altitude >= 0)
);


CREATE TABLE ROUTE(
	id		NUMBER(4)	NOT NULL,
	src		VARCHAR(3)	NOT NULL,
	dest		VARCHAR(3)	NOT NULL,
	codeshare	CHAR(1)		NULL,
	stops		NUMBER(2)	NOT NULL,
	CONSTRAINT ROUTE_pkey PRIMARY KEY (id),
	CONSTRAINT ROUTE_fkey1 FOREIGN KEY (src)
		REFERENCES AIRPORT(iata),
	CONSTRAINT ROUTE_fkey2 FOREIGN KEY (dest)
		REFERENCES AIRPORT(iata),
	CONSTRAINT codeshare_check CHECK ( codeshare = 'y' OR codeshare = NULL )
);

CREATE TABLE AIRCRAFT(
	id		NUMBER(3)	NOT NULL,
	name		VARCHAR(30)	NOT NULL,
	inService	NUMBER(3) 	NOT NULL,
	fClass		NUMBER(3)	NOT NULL,
	bClass		NUMBER(3)	NOT NULL,
	peClass		NUMBER(3)	NOT NULL,
	eClass		NUMBER(3)	NOT NULL,
	total		NUMBER(3)	NOT NULL,
	CONSTRAINT AIRCRAFT_pkey PRIMARY KEY (id),
	CONSTRAINT inService_check CHECK (inService >= 0),
	CONSTRAINT fClass_check CHECK (fClass >= 0),
	CONSTRAINT bClass_check CHECK (bClass >= 0),
	CONSTRAINT peClass_check CHECK (peClass >= 0),
	CONSTRAINT eClass_check CHECK (eClass >= 0)
);


CREATE TABLE SCHEDULE(
	id		NUMBER(4)	NOT NULL,
	flightID		VARCHAR(6)	NOT NULL,
	plane		NUMBER(3)	NOT NULL,
	route		NUMBER(4)	NOT NULL,
	depart		VARCHAR(30)	NOT NULL,
	arrive 		VARCHAR(30)	NOT NULL,
	CONSTRAINT SCHEDULE_pkey PRIMARY KEY (id),
	CONSTRAINT SCHEDULE_fkey1 FOREIGN KEY (plane)
		REFERENCES AIRCRAFT(id),
	CONSTRAINT SCHEDULE_fkey2 FOREIGN KEY (route)
		REFERENCES ROUTE(id),
	CONSTRAINT schedule_flightID UNIQUE (flightID)
);



CREATE TABLE TRAVELAGENT(
	id	NUMBER(3)	NOT NULL,
	name	VARCHAR(50)	NOT NULL,
	phone	VARCHAR(20)	NOT NULL,
	email	VARCHAR(50)	NOT NULL,
	CONSTRAINT TRAVELAGENT_pkey PRIMARY KEY (id),
	CONSTRAINT agent_name UNIQUE (name)
);


CREATE TABLE CUSTOMER (
	id		NUMBER(4)	NOT NULL,
	title		CHAR(4)		NOT NULL,
	fName		VARCHAR(20)	NOT NULL,
	lName		VARCHAR(30)	NOT NULL,
	gender		VARCHAR(6)	NOT NULL,
	DOB		DATE		NOT NULL,
	phone		VARCHAR(20)	NOT NULL,
	email		VARCHAR(50)	NOT NULL,
	address		VARCHAR(50)	NOT NULL,
	state		VARCHAR(50)	NULL,
	city		VARCHAR(50)	NOT NULL,
	country		VARCHAR(30)	NOT NULL,
	credCard		VARCHAR(30)	NULL,
	cardNum		NUMBER(30)	NULL,
	freqFly		NUMBER(10)	NULL,
	passport 	VARCHAR(5)	NOT NULL,
	status		VARCHAR(10)	NULL,
	travelAgent	VARCHAR(50)	NULL,
	CONSTRAINT CUSTOMER_pkey PRIMARY KEY (id),
	CONSTRAINT CUSTOMER_fkey1 FOREIGN KEY (travelAgent)
		REFERENCES TRAVELAGENT(name),
	CONSTRAINT freqFly_check CHECK (freqFly >= 0),
	CONSTRAINT passport_check CHECK (passport = 'TRUE' OR passport = 'FALSE'),
	CONSTRAINT status_check CHECK ( status = NULL OR status = 'watch' OR status = 'no fly')		
);


CREATE TABLE SERVICEITEM (
	id		NUMBER(3)	NOT NULL,
	item		VARCHAR(30)	NOT NULL,
	cost		DECIMAL(5,2)	NOT NULL,
	availability	VARCHAR(15) 	NOT NULL,
	CONSTRAINT SERVICEITEM_pkey PRIMARY KEY (id),
	CONSTRAINT cost_check CHECK (cost >= 0),
	CONSTRAINT availability_check CHECK (availability = 'all' OR availability = 'international')
);



CREATE TABLE FLIGHT(
	id		VARCHAR(6)	NOT NULL,
	currFCap	NUMBER(3)	NOT NULL,
	currBCap	NUMBER(3)	NOT NULL,
	currPECap	NUMBER(3)	NOT NULL,
	currECap	NUMBER(3)	NOT NULL,
	CONSTRAINT FLIGHT_pkey PRIMARY KEY (id),
	CONSTRAINT FLIGHT_fkey1 FOREIGN KEY (id)
		REFERENCES SCHEDULE(flightID),
	CONSTRAINT fCap_check CHECK (currFCap >= 0),
	CONSTRAINT bCap_check CHECK (currBCap >= 0),
	CONSTRAINT peCap_check CHECK (currPECap >= 0),
	CONSTRAINT eCap_check CHECK (currECap >= 0)
);

CREATE TABLE FLIGHTSERVICE(
	id 		NUMBER(3)	NOT NULL,
	flightID	VARCHAR(6)	NOT NULL,
	serviceItem	NUMBER(3)	NOT NULL,
	amount		NUMBER(3)	NOT NULL,
	CONSTRAINT FLIGHTSERVICE_pkey PRIMARY KEY (id),
	CONSTRAINT FLIGHTSERVICE_fkey1 FOREIGN KEY (flightID)
		REFERENCES SCHEDULE(flightID),
	CONSTRAINT amount_check CHECK (amount >= 0)
);

INSERT INTO AIRPORT VALUES('5','Port Moresby Jacksons Intl','Port Moresby','Papua New Guinea','POM',-9.443383,147.22005,146,10,'U','Pacific/Port_Moresby');


INSERT INTO ROUTE VALUES(1,'POM','POM','Y',0);

INSERT INTO AIRCRAFT VALUES(1,'Airbus A330-200',16,0,36,0,268,304);

INSERT INTO SCHEDULE VALUES(1,'QF5211',1,1,'Thu May 28 01:49:32 EST 2015','Thu May 28 16:18:49 EST 2015');

INSERT INTO TRAVELAGENT VALUES (1,'Flight Centre','9-(124)531-0828','amyers0@quantcast.com');


INSERT INTO CUSTOMER VALUES(1,'Mr','Gerald','Ruiz','Male',TO_DATE('03/05/1976','DD/MM/YYYY'),'5-(218)776-8651','gruiz0@mac.com','213 Northwestern Court','','Meiyuan Xincun','China','jcb',3.5447E+15,5200,'TRUE','','Flight Centre');

INSERT INTO SERVICEITEM VALUES (1,'small meal',15,'all');

INSERT INTO FLIGHT VALUES('QF5211',0,0,0,0);

INSERT INTO FLIGHTSERVICE VALUES(1,'QF5211',1,10);

SELECT FLIGHT.id, SERVICEITEM.item, FLIGHTSERVICE.amount
FROM FLIGHT
	JOIN FLIGHTSERVICE
		ON FLIGHT.id = FLIGHTSERVICE.flightID
	JOIN SERVICEITEM
		ON SERVICEITEM.id = FLIGHTSERVICE.serviceItem;


