SET ECHO ON
SET FEEDBACK ON

DROP TABLE AIRPORT CASCADE CONSTRAINTS PURGE;
DROP TABLE ROUTE CASCADE CONSTRAINTS PURGE;
DROP TABLE AIRCRAFT CASCADE CONSTRAINTS PURGE;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS PURGE;
DROP TABLE TRAVELAGENT CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS PURGE;
DROP TABLE SERVICEITEM CASCADE CONSTRAINTS PURGE;
DROP TABLE FLIGHT CASCADE CONSTRAINTS PURGE;
DROP TABLE FLIGHTSERVICE CASCADE CONSTRAINTS PURGE;